<x-layout :title="__('Discover')">
    <section class="discovery-hero">
        {{-- Headline translations contain only trusted line-break and emphasis markup from lang/*.json. --}}
        <div class="hero-copy"><span class="section-kicker"><span></span>{{ __('YOUR EVERYDAY ALLERGEN COMPANION') }}</span><h1>{!! __('A little scan.<br>A clearer <em>choice.</em>') !!}</h1><p>{{ __('Get to know what’s in your everyday products.') }}<br>{{ __('Search, scan, and find the information that matters to you.') }}</p><div class="hero-actions"><a class="button primary" href="{{ route('scan') }}"><x-icon name="scan"/>{{ __('Scan a product') }} <x-icon name="arrow"/></a><a class="text-link" href="{{ route('settings') }}#allergens">{{ __('Set my allergens') }} <span>↗</span></a></div><div class="hero-features"><span><x-icon name="volume"/>{{ __('Read aloud') }}</span><span><x-icon name="language"/>日本語 / English</span><span><x-icon name="phone"/>{{ __('Made for your phone') }}</span></div></div>
        <div class="hero-art"><x-grocery-art/><div class="art-caption"><span class="caption-icon"><x-icon name="search"/></span><div><strong>{{ __('Know a little more.') }}</strong><small>{{ __('Product details, in your pocket.') }}</small></div><span class="caption-sparkle">✦</span></div><span class="art-corner-label">{{ __('SCAN. READ. UNDERSTAND.') }}</span></div>
    </section>
    <a class="allergen-banner" href="{{ route('settings') }}#allergens"><span class="banner-symbol"><x-icon name="user"/></span><div><strong>{{ __('Your preferences. Your perspective.') }}</strong><p data-allergen-summary>{{ __('Select your allergens to highlight matching ingredients as you explore.') }}</p></div><span class="banner-link">{{ __('Personalize') }} <x-icon name="arrow"/></span></a>
    <section id="catalog" class="catalog-section">
        <div class="section-heading"><div><span class="section-kicker">{{ __('A LOOK INSIDE YOUR EVERYDAY') }}</span><h2>{{ __('Explore the catalog') }}<span class="heading-dot">.</span></h2><p>{{ __('Search products and check their allergen information.') }}</p></div><span class="subtle-pill">{{ __(':count products', ['count' => $products->total()]) }}</span></div>
        <form class="catalog-search" action="{{ route('discover') }}#catalog" method="GET"><label for="product-search" class="sr-only">{{ __('Search products') }}</label><x-icon name="search"/><input id="product-search" name="q" value="{{ $search }}" placeholder="{{ __('Search a product name or barcode…') }}" maxlength="100" type="search">@if($category)<input type="hidden" name="category" value="{{ $category }}">@endif<button class="button primary" type="submit">{{ __('Search') }}</button></form>
        @error('q')<p role="alert" class="error-text">{{ $message }}</p>@enderror
        <nav class="category-tabs" aria-label="{{ __('Product categories') }}">
            @foreach(['' => 'All products', 'Food' => 'Food', 'Drinks' => 'Drinks', 'Snacks' => 'Snacks', 'Daily' => 'Everyday essentials'] as $value => $label)<a href="{{ route('discover', array_filter(['q' => $search, 'category' => $value])) }}#catalog" class="{{ $category === $value ? 'selected' : '' }}" @if($category === $value) aria-current="true" @endif>{{ __($label) }}</a>@endforeach
        </nav>
        @if($search)<div class="search-summary">{{ __('Results for “:search”', ['search' => $search]) }}<a class="text-link" href="{{ route('discover') }}#catalog">{{ __('Clear search') }} ×</a></div>@endif
        <div class="product-grid">@forelse($products as $product)<x-product-card :product="$product"/>@empty<div class="shop-empty"><x-icon name="search"/><h3>{{ __('No products found.') }}</h3><p>{{ __('Try another name or barcode.') }}</p><a class="button secondary" href="{{ route('discover') }}#catalog">{{ __('Explore all products') }}</a></div>@endforelse</div>
        <div class="pagination">{{ $products->links() }}</div>
    </section>
    <section class="how-it-works"><div><span class="section-kicker">{{ __('SMALL STEPS. CLEARER INFORMATION.') }}</span><h2>{!! __('A companion for<br>your everyday shop.') !!}</h2></div><div><span class="step-number">01</span><h3>{{ __('Make it yours') }}</h3><p>{{ __('Select the allergens you want highlighted. Change them anytime.') }}</p></div><div><span class="step-number">02</span><h3>{{ __('Find a product') }}</h3><p>{{ __('Scan its barcode or search our product catalog by name.') }}</p></div><div><span class="step-number">03</span><h3>{{ __('Read or listen') }}</h3><p>{{ __('See recorded information in Japanese and English, or have it read aloud.') }}</p></div></section>
    <div class="data-note"><x-icon name="info"/><p><strong>{{ __('Check the actual label, every time.') }}</strong> {{ __('Our team records allergen information from product packaging. Records may be incomplete or out of date; always check the actual packaging and manufacturer information. No match does not mean allergen-free.') }}</p></div>
</x-layout>
