<x-layout title="Discover">
    <section class="discovery-hero">
        <div class="hero-copy"><span class="section-kicker"><span></span>YOUR EVERYDAY ALLERGEN COMPANION</span><h1>A little scan.<br>A clearer <em>choice.</em></h1><p>Get to know what’s in your everyday products.<br>Search, scan, and find the information that matters to you.</p><p class="hero-japanese" lang="ja">気になるアレルゲンを、もっとわかりやすく。</p><div class="hero-actions"><a class="button primary" href="{{ route('scan') }}"><x-icon name="scan"/>Scan a product <x-icon name="arrow"/></a><a class="text-link" href="{{ route('settings') }}#allergens">Set my allergens <span>↗</span></a></div><div class="hero-features"><span><x-icon name="volume"/>Read aloud</span><span><x-icon name="language"/>日本語 / English</span><span><x-icon name="phone"/>Made for your phone</span></div></div>
        <div class="hero-art"><x-grocery-art/><div class="art-caption"><span class="caption-icon"><x-icon name="search"/></span><div><strong>Know a little more.</strong><small>Product details, in your pocket.</small></div><span class="caption-sparkle">✦</span></div><span class="art-corner-label">SCAN. READ. UNDERSTAND.</span></div>
    </section>
    <a class="allergen-banner" href="{{ route('settings') }}#allergens"><span class="banner-symbol"><x-icon name="user"/></span><div><strong>Your preferences. Your perspective.</strong><p data-allergen-summary>Select your allergens to highlight matching ingredients as you explore.</p></div><span class="banner-link">Personalize <x-icon name="arrow"/></span></a>
    <section id="catalog" class="catalog-section">
        <div class="section-heading"><div><span class="section-kicker">A LOOK INSIDE YOUR EVERYDAY</span><h2>Explore the catalog<span class="heading-dot">.</span></h2><p>商品を探して、アレルゲン情報を確認。</p></div><span class="subtle-pill">{{ $products->total() }} products</span></div>
        <form class="catalog-search" action="{{ route('discover') }}#catalog" method="GET"><label for="product-search" class="sr-only">Search products / 商品検索</label><x-icon name="search"/><input id="product-search" name="q" value="{{ $search }}" placeholder="Search a product, 商品名, or barcode…" maxlength="100" type="search">@if($category)<input type="hidden" name="category" value="{{ $category }}">@endif<button class="button primary" type="submit">Search</button></form>
        @error('q')<p role="alert" class="error-text">{{ $message }}</p>@enderror
        <nav class="category-tabs" aria-label="Product categories">
            @foreach(['' => 'All products', 'Food' => 'Food', 'Drinks' => 'Drinks', 'Snacks' => 'Snacks', 'Daily' => 'Everyday essentials'] as $value => $label)<a href="{{ route('discover', array_filter(['q' => $search, 'category' => $value])) }}#catalog" class="{{ $category === $value ? 'selected' : '' }}" @if($category === $value) aria-current="true" @endif>{{ $label }}</a>@endforeach
        </nav>
        @if($search)<div class="search-summary">Results for “{{ $search }}”<a class="text-link" href="{{ route('discover') }}#catalog">Clear search ×</a></div>@endif
        <div class="product-grid">@forelse($products as $product)<x-product-card :product="$product"/>@empty<div class="shop-empty"><x-icon name="search"/><h3>No products found.</h3><p>Try another name or barcode. / 別の商品名で検索してください。</p><a class="button secondary" href="{{ route('discover') }}#catalog">Explore all products</a></div>@endforelse</div>
        <div class="pagination">{{ $products->links() }}</div>
    </section>
    <section class="how-it-works"><div><span class="section-kicker">SMALL STEPS. CLEARER INFORMATION.</span><h2>A companion for<br>your everyday shop.</h2></div><div><span class="step-number">01</span><h3>Make it yours</h3><p>Select the allergens you want highlighted. Change them anytime.</p></div><div><span class="step-number">02</span><h3>Find a product</h3><p>Scan its barcode or search our product catalog by name.</p></div><div><span class="step-number">03</span><h3>Read or listen</h3><p>See recorded information in Japanese and English, or have it read aloud.</p></div></section>
    <div class="data-note"><x-icon name="info"/><p><strong>A learning project, with sample products.</strong> Demo records are fictional. Allergen coverage is limited; always check the actual packaging and manufacturer information. No match does not mean allergen-free.<small lang="ja">卒業制作のデモです。実際の商品表示・メーカー情報を必ず確認してください。</small></p></div>
</x-layout>
