<div class="content-page">
    <div class="page-intro"><div><h2>Your products, clearly understood.</h2><p>商品とアレルゲン情報を、ひとつの場所で管理。</p></div><button class="button primary" wire:click="edit"><x-icon name="plus"/>Add product / 商品追加</button></div>
    @if(session('message'))<div class="notice" role="status">{{ session('message') }}</div>@endif
    <div class="panel"><div class="table-toolbar"><h3>Product catalog <span class="count-tag">{{ $products->total() }}</span></h3><label class="search-field"><x-icon name="search"/><span class="sr-only">Search products</span><input wire:model.live.debounce.250ms="search" placeholder="Search name or barcode…"></label></div>
    <div class="table-scroll"><table><thead><tr><th>Product / 商品</th><th>Barcode</th><th>Allergen information</th><th>Status</th><th>Actions</th></tr></thead><tbody>
    @forelse($products as $product)<tr wire:key="row-{{ $product->id }}"><td><div class="table-product"><span>{{ $product->icon }}</span><div><strong>{{ $product->name_ja }}</strong><small>{{ $product->name_en }} · {{ $product->size }}</small>@if($product->is_demo)<span class="sample-inline">FICTIONAL DEMO</span>@endif</div></div></td><td class="mono">{{ $product->barcode }}</td><td>@if($product->information_status === 'unknown')<span class="badge amber">未確認 / Unknown</span>@else<div class="badge-list">@forelse($product->allergens as $allergen)<span class="badge">{{ $allergen->name_ja }} / {{ $allergen->name_en }}</span>@empty<span class="muted">記録上の該当なし / None recorded</span>@endforelse</div><small>Checked {{ $product->verified_at?->format('Y/m/d') }}</small>@endif</td><td><span class="status-pill {{ $product->is_active ? '' : 'inactive' }}"><span></span>{{ $product->is_active ? 'Active' : 'Archived' }}</span></td><td><div class="table-actions"><button class="text-button" wire:click="edit({{ $product->id }})">Edit</button><button class="text-button" wire:click="toggleActive({{ $product->id }})" wire:confirm="Change catalog visibility? / 商品の公開状態を変更しますか？">{{ $product->is_active ? 'Archive' : 'Restore' }}</button></div></td></tr>
    @empty<tr><td colspan="5" class="empty-state">No products found. 商品がありません。</td></tr>@endforelse
    </tbody></table></div><div class="pagination">{{ $products->links() }}</div></div>
    <p class="muted">Archiving hides a product from search, barcode lookup, and saved lists. アーカイブした商品はアプリに表示されません。</p>
    @if($editing)
    <div class="modal-backdrop" x-data x-init="$nextTick(() => $refs.first.focus())" @keydown.escape.window="$wire.set('editing', false)"><section class="edit-modal" role="dialog" aria-modal="true" aria-labelledby="product-title" x-trap.inert.noscroll="true"><div class="dialog-heading"><div><span class="eyebrow">PRODUCT DETAILS</span><h2 id="product-title">{{ $productId ? 'Edit product / 商品編集' : 'Add product / 商品追加' }}</h2></div><button class="icon-button" wire:click="$set('editing', false)" aria-label="Close product form">✕</button></div>
    <form wire:submit="save">
    @if($errors->any())<div class="notice danger" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="form-grid"><label>Barcode / バーコード<input x-ref="first" wire:model="form.barcode" required maxlength="50"></label><label>Product name / 商品名<input wire:model="form.name_ja" required maxlength="255"></label><label>English name<input wire:model="form.name_en" required maxlength="255"></label><label>Size / 内容量<input wire:model="form.size" required maxlength="100"></label><label>Category / 分類<select wire:model="form.category"><option>Food</option><option>Drinks</option><option>Snacks</option><option>Daily</option></select></label><label>Icon<select wire:model="form.icon">@foreach(['📦','🥛','🍞','🍙','🍵','🍫','🍜','🍎','🍪','🧃','🥗','🧴'] as $icon)<option>{{ $icon }}</option>@endforeach</select></label></div>
    <div class="form-section"><h3>Allergen information / アレルゲン情報</h3><p class="muted">Select once. Japanese and English use the same allergen record.</p><div class="checkbox-grid">@foreach($allergens as $allergen)<label><input type="checkbox" wire:model="allergenIds" value="{{ $allergen->id }}">{{ $allergen->name_ja }} / {{ $allergen->name_en }}</label>@endforeach</div><p class="small muted">Demo vocabulary only; this is not a complete labeling checklist. 実商品の登録前に対象項目を整備してください。</p></div>
    <div class="form-grid"><label>Information status / 確認状態<select wire:model="form.information_status"><option value="unknown">Unknown / 情報未確認</option><option value="recorded">Recorded / 情報を確認・記録済</option></select></label><label>Checked date / 確認日<input type="date" wire:model="form.verified_at" max="{{ now()->toDateString() }}"></label><label class="full">Source / 情報元<input wire:model="form.source" placeholder="Package label photo or source reference" maxlength="255"></label></div>
    <label class="checkbox-label"><input type="checkbox" wire:model="form.is_demo">Fictional demo product / 架空のデモ商品</label><div class="modal-actions"><button type="button" class="button secondary" wire:click="$set('editing', false)">Cancel</button><button class="button primary" type="submit" wire:loading.attr="disabled">Save product / 保存</button></div>
    </form></section></div>
    @endif
</div>
