<div class="content-page">
    <div class="page-intro"><div><h2>{{ __('Your products, clearly understood.') }}</h2><p>{{ __('Manage products and allergen information in one place.') }}</p></div><button class="button primary" wire:click="edit"><x-icon name="plus"/>{{ __('Add product') }}</button></div>
    @if(session('message'))<div class="notice" role="status">{{ session('message') }}</div>@endif
    <div class="panel"><div class="table-toolbar"><h3>{{ __('Product catalog') }} <span class="count-tag">{{ $products->total() }}</span></h3><label class="search-field"><x-icon name="search"/><span class="sr-only">{{ __('Search products') }}</span><input wire:model.live.debounce.250ms="search" placeholder="{{ __('Search name or barcode…') }}"></label></div>
    <div class="table-scroll"><table><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Barcode') }}</th><th>{{ __('Allergen information') }}</th><th>{{ __('Status') }}</th><th>{{ __('Actions') }}</th></tr></thead><tbody>
    @forelse($products as $product)<tr wire:key="row-{{ $product->id }}"><td><div class="table-product"><span>{{ $product->icon }}</span><div><strong>{{ $product->name_ja }}</strong><small>{{ $product->name_en }} · {{ $product->size }}</small>@if($product->is_demo)<span class="sample-inline">{{ __('SAMPLE') }}</span>@endif</div></div></td><td class="mono">{{ $product->barcode }}</td><td>@if($product->information_status === 'unknown')<span class="badge amber">{{ __('Unknown') }}</span>@else<div class="badge-list">@forelse($product->allergens as $allergen)<span class="badge">{{ $allergen->name }}</span>@empty<span class="muted">{{ __('None recorded') }}</span>@endforelse</div><small>{{ __('Checked :date', ['date' => $product->verified_at?->format('Y/m/d')]) }}</small>@endif</td><td><span class="status-pill {{ $product->is_active ? '' : 'inactive' }}"><span></span>{{ $product->is_active ? __('Active') : __('Archived') }}</span></td><td><div class="table-actions"><button class="text-button" wire:click="edit({{ $product->id }})">{{ __('Edit') }}</button><button class="text-button" wire:click="toggleActive({{ $product->id }})" wire:confirm="{{ __('Change catalog visibility?') }}">{{ $product->is_active ? __('Archive') : __('Restore') }}</button></div></td></tr>
    @empty<tr><td colspan="5" class="empty-state">{{ __('No products found.') }}</td></tr>@endforelse
    </tbody></table></div><div class="pagination">{{ $products->links() }}</div></div>
    <p class="muted">{{ __('Archiving hides a product from search, barcode lookup, and saved lists.') }}</p>
    @if($editing)
    <div class="modal-backdrop" x-data x-init="$nextTick(() => $refs.first.focus())" @keydown.escape.window="$wire.set('editing', false)"><section class="edit-modal" role="dialog" aria-modal="true" aria-labelledby="product-title" x-trap.inert.noscroll="true"><div class="dialog-heading"><div><span class="eyebrow">{{ __('PRODUCT DETAILS') }}</span><h2 id="product-title">{{ $productId ? __('Edit product') : __('Add product') }}</h2></div><button class="icon-button" wire:click="$set('editing', false)" aria-label="{{ __('Close product form') }}">✕</button></div>
    <form wire:submit="save">
    @if($suggestionId)<div class="notice warning" role="note">{{ __('Filled in from a shopper suggestion. Check every field against the package label before saving. Leave the status as Unknown until the allergens are confirmed.') }}</div>@endif
    @if($errors->any())<div class="notice danger" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="form-grid"><label>{{ __('Barcode') }}<input x-ref="first" wire:model="form.barcode" required maxlength="50"></label><label>{{ __('Japanese name') }}<input wire:model="form.name_ja" required maxlength="255" lang="ja"></label><label>{{ __('English name') }}<input wire:model="form.name_en" required maxlength="255" lang="en"></label><label>{{ __('Size') }}<input wire:model="form.size" required maxlength="100"></label><label>{{ __('Category') }}<select wire:model="form.category">@foreach(['Food', 'Drinks', 'Snacks', 'Daily'] as $category)<option value="{{ $category }}">{{ __($category) }}</option>@endforeach</select></label><label>{{ __('Icon') }}<select wire:model="form.icon">@foreach(['📦','🥛','🍞','🍙','🍵','🍫','🍜','🍎','🍪','🧃','🥗','🧴'] as $icon)<option>{{ $icon }}</option>@endforeach</select></label></div>
    <div class="form-section"><h3>{{ __('Allergen information') }}</h3><p class="muted">{{ __('Select once. Japanese and English use the same allergen record.') }}</p><div class="checkbox-grid">@foreach($allergens as $allergen)<label><input type="checkbox" wire:model="allergenIds" value="{{ $allergen->id }}">{{ $allergen->name_ja }} / {{ $allergen->name_en }}</label>@endforeach</div><p class="small muted">{{ __('Japan’s mandatory and recommended labeling items. Record exactly what the package label declares.') }}</p></div>
    <div class="form-grid"><label>{{ __('Information status') }}<select wire:model="form.information_status"><option value="unknown">{{ __('Unknown') }}</option><option value="recorded">{{ __('Recorded') }}</option></select></label><label>{{ __('Checked date') }}<input type="date" wire:model="form.verified_at" max="{{ now()->toDateString() }}"></label><label class="full">{{ __('Source') }}<input wire:model="form.source" placeholder="{{ __('Package label photo or source reference') }}" maxlength="255"></label></div>
    <label class="checkbox-label"><input type="checkbox" wire:model="form.is_demo">{{ __('Sample record (not real label information)') }}</label><div class="modal-actions"><button type="button" class="button secondary" wire:click="$set('editing', false)">{{ __('Cancel') }}</button><button class="button primary" type="submit" wire:loading.attr="disabled">{{ __('Save product') }}</button></div>
    </form></section></div>
    @endif
</div>
